[package]
name = "krnl-example"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[features]
half = ["dep:half", "dep:half-reduction"]

[dependencies]
half = { version = "=2.3.1", default-features = false, optional = true }
libm = { version = "=0.2.8", default-features = false, optional = true }
krnl = { git = "https://github.com/jlogan03/krnl", branch = "jlogan/update-deps" }
num-synth = { git = "ssh://git@github.com/jlogan03/num-synth", branch = "main" }
half-reduction = { path = "half-reduction", optional = true }
deimos_numerics = { git = "https://github.com/deimoscontrols/deimos", branch = "main", default-features = false }

[dev-dependencies]
rand = "0.9"
rayon = "1.12"
num_cpus = "1.17"

[package.metadata.krnlc]
features = ["half"]

[package.metadata.krnlc.dependencies]
# Share these dependencies with krnlc to preserve compatible versions.
half = {}
libm = {}
deimos_numerics = {}
half-reduction = {}
num-synth = {}

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_arch, values("spirv"))',
    'cfg(krnlc)',
] }
